apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prod-autoscale
  namespace: test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: prod-demo-nginx
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
